eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: transaction
              uri: lb://transaction-service
              predicates:
                - Path=/transaction/**